[build]
  command = "npm install --legacy-peer-deps && ng build"
  publish = "dist/portfolio/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
